#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_CONFIG="$ROOT_DIR/config/kinoapi.local.json"
OUTPUT_DIR="$ROOT_DIR/source/config"
OUTPUT_FILE="$OUTPUT_DIR/KinoConfig.brs"

if [[ ! -f "$LOCAL_CONFIG" ]]; then
  echo "Missing config/kinoapi.local.json. Copy config/kinoapi.example.json and add KinoAPI credentials." >&2
  exit 1
fi

python3 - "$LOCAL_CONFIG" "$OUTPUT_FILE" <<'PY'
import json
import os
import sys

local_config = sys.argv[1]
output_file = sys.argv[2]

with open(local_config, encoding="utf-8") as config_file:
    config = json.load(config_file)

client_id = config.get("client_id", "")
client_secret = config.get("client_secret", "")

if not client_id or not client_secret:
    print(
        "config/kinoapi.local.json must contain non-empty client_id and client_secret.",
        file=sys.stderr,
    )
    sys.exit(1)

if client_id == "replace-with-client-id" or client_secret == "replace-with-client-secret":
    print(
        "config/kinoapi.local.json still contains example credential values.",
        file=sys.stderr,
    )
    sys.exit(1)


def brs_string(value):
    parts = []
    chunk = []

    def flush_chunk():
        if chunk:
            parts.append('"' + "".join(chunk) + '"')
            chunk.clear()

    for char in value:
        code = ord(char)
        if char == '"':
            chunk.append('""')
        elif char == "\n":
            flush_chunk()
            parts.append("Chr(10)")
        elif char == "\r":
            flush_chunk()
            parts.append("Chr(13)")
        elif char == "\t":
            flush_chunk()
            parts.append("Chr(9)")
        elif code < 32:
            flush_chunk()
            parts.append(f"Chr({code})")
        else:
            chunk.append(char)

    flush_chunk()
    return " + ".join(parts) if parts else '""'


content = """' Generated by scripts/generate-config.sh. Do not edit or commit.
function KinoConfig() as Object
    return {
        apiBaseUrl: "https://api.service-kp.com"
        clientId: __CLIENT_ID__
        clientSecret: __CLIENT_SECRET__
    }
end function
"""

content = content.replace("__CLIENT_ID__", brs_string(client_id))
content = content.replace("__CLIENT_SECRET__", brs_string(client_secret))

os.makedirs(os.path.dirname(output_file), exist_ok=True)
with open(output_file, "w", encoding="utf-8") as output:
    output.write(content)
PY

echo "Generated source/config/KinoConfig.brs"
