#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/source/config"
OUTPUT_FILE="$OUTPUT_DIR/BuildInfo.brs"

APP_VERSION="${APP_VERSION:-0.0.1}"
APP_SHA="${APP_SHA:-$(git -C "$ROOT_DIR" rev-parse --short=7 HEAD 2>/dev/null || printf 'unknown')}"
APP_SHA="${APP_SHA:0:7}"

if [[ ! "$APP_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "APP_VERSION must start with a semantic version such as 0.0.1." >&2
  exit 1
fi

python3 - "$OUTPUT_FILE" "$APP_VERSION" "$APP_SHA" <<'PY'
import os
import sys

output_file, version, sha = sys.argv[1:]


def brs_string(value):
    return '"' + value.replace('"', '""') + '"'


content = f"""' Generated by scripts/generate-build-info.sh. Do not edit or commit.
function BuildInfo() as Object
    return {{
        version: {brs_string(version)}
        sha: {brs_string(sha)}
        displayVersion: {brs_string(version + "-" + sha)}
    }}
end function
"""

os.makedirs(os.path.dirname(output_file), exist_ok=True)
with open(output_file, "w", encoding="utf-8") as output:
    output.write(content)
PY

echo "Generated source/config/BuildInfo.brs ($APP_VERSION-$APP_SHA)"
